server:
  port: 8888

spring:
  config:
    activate:
      on-profile: prod

  cache:
    type: simple
    cache-names: daily-popular
    simple:
      cache-name-configs:
        products:
          time-to-live: 86400000 # 24시간

  datasource:
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG